stages:
  - test
  # - build_backend
  # - build_frontend
  # - push_to_docker_hub

variables:
  DOCKER_HUB_REPO: "amgad226"
  BACKEND_IMAGE_NAME: "mesh-b"
  FRONTEND_IMAGE_NAME: "mesh-f"

test:
  stage: test
  script:
    - ls
