stages:
  # - build_backend
  - build_frontend
# 
variables:
  DOCKER_HUB_REPO: "amgad226"
  BACKEND_IMAGE_NAME: "mesh-b"
  FRONTEND_IMAGE_NAME: "mesh-f"
  API_ENDPOINT: "https://wizardly-brahmagupta.212-227-199-24.plesk.page/docker-pull"

# build_backend:
#   stage: build_backend
#   image: docker:19.03.12
#   services:
#     - docker:19.03.12-dind
#   script:
#     - docker build -t $DOCKER_HUB_REPO/$BACKEND_IMAGE_NAME .
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#     - docker push $DOCKER_HUB_REPO/$BACKEND_IMAGE_NAME
#     # - curl -X POST "$API_ENDPOINT?image=mesh-b&token=TE*%3C@YRD@!j%3EsaAsdjfaY%3E"


build_frontend:
  stage: build_frontend
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
    - cd client
    - docker build -t $DOCKER_HUB_REPO/$FRONTEND_IMAGE_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $DOCKER_HUB_REPO/$FRONTEND_IMAGE_NAME
    # - curl -X POST "$API_ENDPOINT?image=mesh-t&token=TE*%3C@YRD@!j%3EsaAsdjfaY%3E"
