version: '3'
services:
  backend:
    image: amgad226/mesh-b
    build: .
    ports:
      - "3001:3001"

  frontend:
    image: amgad226/mesh-f
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
